aeron_term_buffer_sparse_file=false
aeron_pre_touch_mapped_memory=true
aeron_socket_so_sndbuf=2m
aeron_socket_so_rcvbuf=2m
aeron_rcv_initial_window_length=2m
aeron_threading_mode=DEDICATED
aeron_sender_idle_strategy=noop
aeron_receiver_idle_strategy=noop
aeron_conductor_idle_strategy=spin
agrona_disable_bounds_checks=true
